# Laboratorio 3 - Análsis de Datos con Python

## Parte 1: Numpy
Para los ejercicios siguientes genere el código que considere para resolver el problema que se le plantea.

### 1) ¿Cuál es el tamaño en bytes de un array de 1000 elementos de tipo booleano?

In [4]:
import numpy as np

# Creamos un array de 1000 elementos de tipo booleano en numpy, en este caso 0's o Falses
mi_array = np.zeros(1000, dtype=bool)

# Calculamos el tamaño en bytes
tamanio_en_bytes_array = mi_array.nbytes

# Imprimimos el resultado
print(f'El tamaño en bytes del array es: {tamanio_en_bytes_array} bytes')


El tamaño en bytes del array es: 1000 bytes


In [5]:
!git init

Initialized empty Git repository in C:/Users/risca/Desktop/Maestria Ciencia de Datos/Ciencia de datos en Python/Ciencia_de_Datos_Python/U/Laboratorio3/.git/


In [6]:
!git add 12002224_Laboratorio3_Numpy_y_Pandas.ipynb

The file will have its original line endings in your working directory


In [7]:
!git commit -m "Primer commit del laboratorio 3"

[master (root-commit) 6bd524f] Primer commit del laboratorio 3
 1 file changed, 103 insertions(+)
 create mode 100644 12002224_Laboratorio3_Numpy_y_Pandas.ipynb


In [8]:
!git branch -M main

In [10]:
!git remote add origin https://github.com/CarlosRisch/Laboratorio3_Numpy_y_Pandas.git

In [11]:
!git push -u origin main

Branch 'main' set up to track remote branch 'main' from 'origin'.


To https://github.com/CarlosRisch/Laboratorio3_Numpy_y_Pandas.git
 * [new branch]      main -> main


### 2) Cree un array cuyos elementos sean los enteros pares en [1,100] y en orden decreciente. Muestre los 10 últimos por pantalla.

In [14]:
import numpy as np

# Se crea un array con enteros pares en el rango [1, 100] en orden decreciente
enteros_pares = np.arange(100, 0, -2)

# mostramos los últimos 10
ultimos_elementos = enteros_pares[-10:]
print('Los últimos 10 elementos son: ')
print(ultimos_elementos)

Los últimos 10 elementos son: 
[20 18 16 14 12 10  8  6  4  2]


In [15]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   12002224_Laboratorio3_Numpy_y_Pandas.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Lab3.zip
	Lab3/
	__MACOSX/

no changes added to commit (use "git add" and/or "git commit -a")


In [16]:
!git add 12002224_Laboratorio3_Numpy_y_Pandas.ipynb

The file will have its original line endings in your working directory


In [17]:
!git commit -m "Segundo Ejercicio del Laboratorio 3 parte I"

[main 19901ec] Segundo Ejercicio del Laboratorio 3 parte I
 1 file changed, 125 insertions(+), 1 deletion(-)


In [18]:
!git push -u origin main

Branch 'main' set up to track remote branch 'main' from 'origin'.


To https://github.com/CarlosRisch/Laboratorio3_Numpy_y_Pandas.git
   6bd524f..19901ec  main -> main


### 3) Dado el array
###### 2 4 5 6
###### 0 3 7 4
###### 8 8 5 2
###### 1 5 6 1
###### Seleccione con una instrucción el subarray de elementos
###### 0 3 7 4
###### Después, seleccione el subarray de elementos
###### 2 5
###### 8 5

In [49]:
# Creo el array especificado con sus subarrays 
mi_array2 = np.array([
    [2, 4, 5, 6],
    [0, 3, 7, 4],
    [8, 8, 5, 2],
    [1, 5, 6, 1]
])

# Obtengo el subarray [0,3,7,4]
print('Selecciono el subarray de elementos [0,3,7,4]')
print(mi_array2[1,:5])

# Obtengo el subarray 
# 2 5
# 8 5
print()
print('Siguiente subarray:')
print(mi_array2[0:3:2, 0:3:2])


Selecciono el subarray de elementos [0,3,7,4]
[0 3 7 4]

Siguiente subarray:
[[2 5]
 [8 5]]


In [50]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   12002224_Laboratorio3_Numpy_y_Pandas.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Lab3.zip
	Lab3/
	__MACOSX/

no changes added to commit (use "git add" and/or "git commit -a")


In [51]:
!git add 12002224_Laboratorio3_Numpy_y_Pandas.ipynb

The file will have its original line endings in your working directory


In [52]:
!git commit -m "Tercer ejercicio del Laboratorio 3 parte I"

[main e4a10e6] Tercer ejercicio del Laboratorio 3 parte I
 1 file changed, 172 insertions(+), 14 deletions(-)


In [53]:
!git push -u origin main

Branch 'main' set up to track remote branch 'main' from 'origin'.


To https://github.com/CarlosRisch/Laboratorio3_Numpy_y_Pandas.git
   19901ec..e4a10e6  main -> main


### 4) Dados los arrays a = [1, 4, 2, 7] y b = [1, 3, 2, 9], obtenga la media aritmética de la diferencia (a-b).

In [58]:
# Declaro los arrays provistos
a = np.array([1, 4, 2, 7])
b = np.array([1, 3, 2, 9])

# Realizo la resta del array a y b
diferencia = a - b

# obtengo la media de diferencia entre a y b
media = np.mean(diferencia)

print(f'La diferencia entre el array {a} y el array {b} es: {diferencia}')
print(f'La media de la diferencia es: {media} ')

La diferencia entre el array [1 4 2 7] y el array [1 3 2 9] es: [ 0  1  0 -2]
La media de la diferencia es: -0.25 


In [59]:
!git status

On branch main
Your branch is up to date with 'origin/main'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   12002224_Laboratorio3_Numpy_y_Pandas.ipynb

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	.ipynb_checkpoints/
	Lab3.zip
	Lab3/
	__MACOSX/

no changes added to commit (use "git add" and/or "git commit -a")
